CREATE TYPE [dbo].[BigGenericTableType] AS TABLE (
    [NumericValue1]  INT             NULL,
    [NumericValue2]  INT             NULL,
    [NumericValue3]  INT             NULL,
    [NumericValue4]  INT             NULL,
    [NumericValue5]  INT             NULL,
    [NumericValue6]  INT             NULL,
    [NumericValue7]  INT             NULL,
    [NumericValue8]  INT             NULL,
    [NumericValue9]  INT             NULL,
    [NumericValue10] INT             NULL,
    [NumericValue11] INT             NULL,
    [NumericValue12] INT             NULL,
    [NumericValue13] INT             NULL,
    [NumericValue14] INT             NULL,
    [NumericValue15] INT             NULL,
    [NumericValue16] INT             NULL,
    [NumericValue17] INT             NULL,
    [NumericValue18] INT             NULL,
    [NumericValue19] INT             NULL,
    [NumericValue20] INT             NULL,
    [TextValue1]     NVARCHAR (MAX)  NULL,
    [TextValue2]     NVARCHAR (MAX)  NULL,
    [TextValue3]     NVARCHAR (MAX)  NULL,
    [TextValue4]     NVARCHAR (MAX)  NULL,
    [TextValue5]     NVARCHAR (MAX)  NULL,
    [TextValue6]     NVARCHAR (MAX)  NULL,
    [TextValue7]     NVARCHAR (MAX)  NULL,
    [TextValue8]     NVARCHAR (MAX)  NULL,
    [BitValue1]      BIT             NULL,
    [BitValue2]      BIT             NULL,
    [BitValue3]      BIT             NULL,
    [BitValue4]      BIT             NULL,
    [BitValue5]      BIT             NULL,
    [BitValue6]      BIT             NULL,
    [BitValue7]      BIT             NULL,
    [BitValue8]      BIT             NULL,
    [DecimalValue1]  DECIMAL (19, 9) NULL,
    [DecimalValue2]  DECIMAL (19, 9) NULL,
    [DecimalValue3]  DECIMAL (19, 9) NULL,
    [DecimalValue4]  DECIMAL (19, 9) NULL,
    [DecimalValue5]  DECIMAL (19, 9) NULL,
    [DecimalValue6]  DECIMAL (19, 9) NULL,
    [DecimalValue7]  DECIMAL (19, 9) NULL,
    [DecimalValue8]  DECIMAL (19, 9) NULL,
    [DateValue1]     DATETIME        NULL,
    [DateValue2]     DATETIME        NULL,
    [DateValue3]     DATETIME        NULL,
    [DateValue4]     DATETIME        NULL,
    [DateValue5]     DATETIME        NULL,
    [DateValue6]     DATETIME        NULL,
    [DateValue7]     DATETIME        NULL,
    [DateValue8]     DATETIME        NULL);

