CREATE TYPE [dbo].[DefaultGenericTableType] AS TABLE (
    [NumericValue1]  INT             NULL,
    [NumericValue2]  INT             NULL,
    [NumericValue3]  INT             NULL,
    [NumericValue4]  INT             NULL,
    [NumericValue5]  INT             NULL,
    [NumericValue6]  INT             NULL,
    [NumericValue7]  INT             NULL,
    [NumericValue8]  INT             NULL,
    [NumericValue9]  INT             NULL,
    [NumericValue10] INT             NULL,
    [TextValue1]     NVARCHAR (MAX)  NULL,
    [TextValue2]     NVARCHAR (MAX)  NULL,
    [TextValue3]     NVARCHAR (MAX)  NULL,
    [TextValue4]     NVARCHAR (MAX)  NULL,
    [TextValue5]     NVARCHAR (MAX)  NULL,
    [TextValue6]     NVARCHAR (MAX)  NULL,
    [TextValue7]     NVARCHAR (MAX)  NULL,
    [TextValue8]     NVARCHAR (MAX)  NULL,
    [TextValue9]     NVARCHAR (MAX)  NULL,
    [TextValue10]    NVARCHAR (MAX)  NULL,
    [BitValue1]      BIT             NULL,
    [BitValue2]      BIT             NULL,
    [BitValue3]      BIT             NULL,
    [BitValue4]      BIT             NULL,
    [BitValue5]      BIT             NULL,
    [BitValue6]      BIT             NULL,
    [BitValue7]      BIT             NULL,
    [BitValue8]      BIT             NULL,
    [BitValue9]      BIT             NULL,
    [BitValue10]     BIT             NULL,
    [MoneyValue1]    MONEY           NULL,
    [MoneyValue2]    MONEY           NULL,
    [MoneyValue3]    MONEY           NULL,
    [MoneyValue4]    MONEY           NULL,
    [MoneyValue5]    MONEY           NULL,
    [MoneyValue6]    MONEY           NULL,
    [MoneyValue7]    MONEY           NULL,
    [MoneyValue8]    MONEY           NULL,
    [MoneyValue9]    MONEY           NULL,
    [MoneyValue10]   MONEY           NULL,
    [DecimalValue1]  DECIMAL (19, 9) NULL,
    [DecimalValue2]  DECIMAL (19, 9) NULL,
    [DecimalValue3]  DECIMAL (19, 9) NULL,
    [DecimalValue4]  DECIMAL (19, 9) NULL,
    [DecimalValue5]  DECIMAL (19, 9) NULL,
    [DecimalValue6]  DECIMAL (19, 9) NULL,
    [DecimalValue7]  DECIMAL (19, 9) NULL,
    [DecimalValue8]  DECIMAL (19, 9) NULL,
    [DecimalValue9]  DECIMAL (19, 9) NULL,
    [DecimalValue10] DECIMAL (19, 9) NULL,
    [DateValue1]     DATETIME        NULL,
    [DateValue2]     DATETIME        NULL,
    [DateValue3]     DATETIME        NULL,
    [DateValue4]     DATETIME        NULL,
    [DateValue5]     DATETIME        NULL,
    [DateValue6]     DATETIME        NULL,
    [DateValue7]     DATETIME        NULL,
    [DateValue8]     DATETIME        NULL,
    [DateValue9]     DATETIME        NULL,
    [DateValue10]    DATETIME        NULL);

